/** Typed access to the graph-generated v17 proof layout. */
import {
  V17_GENERATED_DYNAMIC_TAIL,
  V17_GENERATED_FIXED_PREFIX_BYTES,
  V17_GENERATED_PROOF_FRAMES,
  V17_GENERATED_PROOF_VERSION,
  V17_GENERATED_PROTOCOL_ID_HEX,
} from "../../construction/generated/v17-layout.ts";
import { V17_CONSTRUCTION_GRAPH, v17ProtocolIdHex } from "../../construction/v17-graph.ts";

export type V17GeneratedProofFrame = typeof V17_GENERATED_PROOF_FRAMES[number];
export type V17GeneratedProofFrameId = V17GeneratedProofFrame["id"];
/** Ordered, gap-free fixed-frame inventory generated from the construction graph. */
export const V17_PROOF_FRAMES = V17_GENERATED_PROOF_FRAMES;

const FRAME_BY_ID = new Map(
  V17_GENERATED_PROOF_FRAMES.map((frame) => [frame.id, frame] as const),
);

export function v17ProofFrame(id: V17GeneratedProofFrameId): V17GeneratedProofFrame {
  const frame = FRAME_BY_ID.get(id);
  if (!frame) throw new Error(`unknown generated v17 proof frame ${id}`);
  return frame;
}

export function v17ProofFrameOffset(id: V17GeneratedProofFrameId): number {
  return v17ProofFrame(id).offsetBytes;
}

export function v17ProofFrameEnd(id: V17GeneratedProofFrameId): number {
  const frame = v17ProofFrame(id);
  return frame.offsetBytes + frame.totalBytes;
}

export const V17_PROOF_FIXED_PREFIX_BYTES = V17_GENERATED_FIXED_PREFIX_BYTES;
export const V17_PROOF_OPENING_BODIES_OFFSET = V17_GENERATED_DYNAMIC_TAIL.offsetBytes;
export const V17_PROOF_PROTOCOL_ID = new Uint8Array(
  Buffer.from(V17_GENERATED_PROTOCOL_ID_HEX, "hex"),
);

/** Fail immediately if generated bytes no longer describe the live graph. */
export function assertV17GeneratedProofLayout(): void {
  if (V17_GENERATED_PROOF_VERSION !== V17_CONSTRUCTION_GRAPH.version ||
    V17_GENERATED_PROTOCOL_ID_HEX !== v17ProtocolIdHex() ||
    V17_GENERATED_DYNAMIC_TAIL.id !== "openingBodies" ||
    V17_GENERATED_DYNAMIC_TAIL.offsetBytes !== V17_GENERATED_FIXED_PREFIX_BYTES ||
    V17_GENERATED_PROOF_FRAMES.length !== V17_CONSTRUCTION_GRAPH.proof.frames.length) {
    throw new Error("stale generated v17 proof layout");
  }
  V17_CONSTRUCTION_GRAPH.proof.frames.forEach((source, index) => {
    const generated = V17_GENERATED_PROOF_FRAMES[index];
    if (!generated || generated.id !== source.id ||
      generated.offsetBytes !== source.offsetBytes || generated.itemBytes !== source.itemBytes ||
      generated.itemCount !== source.itemCount || generated.codec !== source.codec ||
      generated.totalBytes !== source.itemBytes * source.itemCount) {
      throw new Error(`generated v17 proof frame mismatch ${source.id}`);
    }
  });
}

assertV17GeneratedProofLayout();
