import { V17_PRODUCTION_ROLE_LAYOUT } from "./v17-role-layout.ts";

/**
 * Bootstrap proof-byte weights used only to compile and measure the first
 * identity-bound bank. Final qualification replaces these with the measured
 * residual-density assignments generated by the v17 linker.
 */
export function localWordVerifierRoleBudget(name: string): number {
  const role = V17_PRODUCTION_ROLE_LAYOUT.find(({ id }) => id === name);
  if (role === undefined) throw new Error(`local-word role budget ${name}`);
  switch (role.kind) {
    case "settlement": return 3_200;
    case "ood-air": return 256;
    case "batch-link-query": return 1_680;
    case "public-boundary-inverses": return 512;
    case "proof-header":
    case "edge-append":
    case "public-boundary-sum":
    case "query-schedule": return 256;
    case "sparse-nullifier": return 1_600;
    case "transcript": return role.part === "interaction" ? 384 : 256;
    case "opening-current": return 1_600;
    case "opening-global": return role.stage === "current" ? 2_400
      : role.stage === "previous" ? 2_200 : 512;
    case "opening-fri": return role.stage === "current" ? 2_400 : 800;
    case "fri-fold-query": return 1_500;
    case "matrix-merkle-leaf": {
      const byMatrix = {
        preprocessed: 3_200,
        original: 3_200,
        interaction: 3_000,
        interactionGlobal: 1_000,
        quotientAndFriMask: 3_400,
      } as const;
      return byMatrix[role.matrix];
    }
    case "matrix-merkle-parent":
    case "fri-merkle-parent": return 3_900;
    case "fri-merkle-leaf": return 1_500;
  }
}

const verifierRoles = V17_PRODUCTION_ROLE_LAYOUT.slice(1);
if (V17_PRODUCTION_ROLE_LAYOUT[0]?.kind !== "settlement") {
  throw new Error("local-word settlement role order");
}

/** Graph-derived semantic input order shared by partitioner and VM bank. */
export const LOCAL_WORD_CANONICAL_ROLE_NAMES: readonly string[] = Object.freeze(
  verifierRoles.map(({ id }) => id),
);

export function localWordCanonicalCarrierBudgets(roleNames: readonly string[]): readonly number[] {
  if (roleNames.length !== verifierRoles.length ||
    roleNames.some((name, item) => name !== verifierRoles[item]!.id) ||
    new Set(roleNames).size !== roleNames.length) {
    throw new Error("local-word canonical carrier roles");
  }
  const budgets = V17_PRODUCTION_ROLE_LAYOUT.map(({ id }) => localWordVerifierRoleBudget(id));
  if (budgets.some((budget) => !Number.isInteger(budget) || budget < 256)) {
    throw new Error("local-word canonical carrier budgets");
  }
  return budgets;
}

export const LOCAL_WORD_CARRIER_BUDGETS = localWordCanonicalCarrierBudgets(
  LOCAL_WORD_CANONICAL_ROLE_NAMES,
);
