import { Ajv2020 } from "ajv/dist/2020.js";
import {
  V17_CONSTRUCTION_GRAPH,
  V17_ELASTIC_PREFIX_SCALE,
  V17_MATRIX_NAMES,
  V17_MAXIMUM_CANONICAL_PROOF_BYTES,
  V17_PROOF_VERSION,
  V17_ROLE_KINDS,
  V17_TRANSCRIPT_ROLE_PARTS,
  buildV17VerifierPlan,
  canonicalV17Json,
  createPendingV17Qualification,
  type V17ConstructionGraph,
  v17ProtocolIdHex,
  validateV17ConstructionGraph,
} from "./v17-graph.ts";

export const V17_GENERATED_ARTIFACT_PATHS = [
  "src/construction/generated/v17-layout.ts",
  "src/construction/generated/v17-layout.rs",
  "src/construction/generated/v17-verifier-plan.json",
  "src/construction/generated/v17-verifier-plan.schema.json",
  "src/construction/generated/v17-qualification.json",
] as const;

export type V17GeneratedArtifactPath = typeof V17_GENERATED_ARTIFACT_PATHS[number];
export type V17GeneratedArtifacts = Readonly<Record<V17GeneratedArtifactPath, string>>;

function prettyCanonicalJson(value: unknown): string {
  return `${JSON.stringify(JSON.parse(canonicalV17Json(value)), null, 2)}\n`;
}

function typescriptLayout(graph: V17ConstructionGraph, protocolIdHex: string): string {
  const frames = graph.proof.frames.map((frame) => ({
    id: frame.id,
    offsetBytes: frame.offsetBytes,
    itemBytes: frame.itemBytes,
    itemCount: frame.itemCount,
    totalBytes: frame.itemBytes * frame.itemCount,
    codec: frame.codec,
  }));
  return `// Generated by scripts/generate-v17-construction.ts. Do not edit.\n` +
    `export const V17_GENERATED_PROOF_VERSION = ${V17_PROOF_VERSION} as const;\n` +
    `export const V17_GENERATED_PROTOCOL_ID_HEX = ${JSON.stringify(protocolIdHex)} as const;\n` +
    `export const V17_GENERATED_FOUNDATION = ${JSON.stringify(graph.foundation, null, 2)} as const;\n` +
    `export const V17_GENERATED_FIXED_PREFIX_BYTES = ${graph.proof.dynamicTail.offsetBytes} as const;\n` +
    `export const V17_GENERATED_DYNAMIC_TAIL = ${JSON.stringify(graph.proof.dynamicTail, null, 2)} as const;\n` +
    `export const V17_GENERATED_PROOF_FRAMES = ${JSON.stringify(frames, null, 2)} as const;\n` +
    `export const V17_GENERATED_TRANSCRIPT_PHASES = ${JSON.stringify(graph.transcript, null, 2)} as const;\n` +
    `export const V17_GENERATED_COMMITMENTS = ${JSON.stringify(graph.commitments, null, 2)} as const;\n` +
    `export const V17_GENERATED_FRI_FOLD_LOGS = ${JSON.stringify(graph.foundation.friFoldLogs)} as const;\n` +
    `export const V17_GENERATED_FRI_FOLD_CHALLENGE_COUNTS = ${JSON.stringify(graph.foundation.friFoldChallengeCounts)} as const;\n` +
    `export const V17_GENERATED_ELASTIC_PREFIX_SCALE = ${V17_ELASTIC_PREFIX_SCALE} as const;\n` +
    `export const V17_GENERATED_MAXIMUM_PROOF_BYTES = ${V17_MAXIMUM_CANONICAL_PROOF_BYTES} as const;\n` +
    `export const V17_GENERATED_ALLOCATION_POLICY = ${JSON.stringify(graph.allocation, null, 2)} as const;\n` +
    `export const V17_GENERATED_ROM_POLICY = ${JSON.stringify(graph.rom, null, 2)} as const;\n`;
}

function rustIdentifier(value: string): string {
  return value.replaceAll(/[^A-Za-z0-9]/g, "_").toUpperCase();
}

function rustLayout(graph: V17ConstructionGraph, protocolIdHex: string): string {
  const protocolBytes = Array.from(Buffer.from(protocolIdHex, "hex"), (byte) => `0x${byte.toString(16).padStart(2, "0")}`);
  const frameRows = graph.proof.frames.map((frame) =>
    `    ProofFrame { id: ${JSON.stringify(frame.id)}, offset_bytes: ${frame.offsetBytes}, item_bytes: ${frame.itemBytes}, item_count: ${frame.itemCount} },`)
    .join("\n");
  const frameConstants = graph.proof.frames.map((frame) =>
    `pub const ${rustIdentifier(frame.id)}_OFFSET: usize = ${frame.offsetBytes};`)
    .join("\n");
  const roundRows = graph.foundation.roundGrinding.map((round) =>
    `    RoundGrinding { id: ${JSON.stringify(round.id)}, bits: ${round.bits} },`)
    .join("\n");
  const merkleRows = graph.commitments.map((commitment) =>
    `    MerkleCommitment { id: ${JSON.stringify(commitment.id)}, label: ${JSON.stringify(commitment.hashLabel)}, log_rows: ${commitment.domainLog}, row_bytes: ${commitment.rowBytes}, leaf_shards: ${commitment.leafShards}, quartet_first: ${commitment.arities[0] === 4}, verifier_cuts: &[${commitment.verifierCuts.join(", ")}] },`)
    .join("\n");
  return `// Generated by scripts/generate-v17-construction.ts. Do not edit.\n` +
    `pub const V17_PROOF_VERSION: u8 = ${V17_PROOF_VERSION};\n` +
    `pub const V17_RELATION_CONSTRUCTION_VERSION: u8 = ${graph.foundation.relationConstructionVersion};\n` +
    `pub const V17_PROTOCOL_ID: [u8; 32] = [${protocolBytes.join(", ")}];\n` +
    `pub const V17_FIXED_PREFIX_BYTES: usize = ${graph.proof.dynamicTail.offsetBytes};\n` +
    `pub const V17_RELATION_LOG: u8 = ${graph.foundation.relationLog};\n` +
    `pub const V17_FUNCTION_DEGREE_LOG: u8 = ${graph.foundation.functionDegreeLog};\n` +
    `pub const V17_QUOTIENT_DEGREE_LOG: u8 = ${graph.foundation.quotientDegreeLog};\n` +
    `pub const V17_EVALUATION_LOG: u8 = ${graph.foundation.evaluationLog};\n` +
    `pub const V17_QUERIES: usize = ${graph.foundation.queries};\n` +
    `pub const V17_OOD_VALUE_COUNT: usize = ${graph.foundation.oodValueCount};\n` +
    `pub const V17_DEGREE_CORRECTED_BATCH_WIDTH: usize = ${graph.foundation.degreeCorrectedBatchWidth};\n` +
    `pub const V17_GRINDING_NONCE_BYTES: usize = ${graph.foundation.grindingNonce.serializedBytes};\n` +
    `pub const V17_ELASTIC_PREFIX_SCALE: usize = ${V17_ELASTIC_PREFIX_SCALE};\n` +
    `pub const V17_MAXIMUM_PROOF_BYTES: usize = ${V17_MAXIMUM_CANONICAL_PROOF_BYTES};\n` +
    `pub const V17_OPCOST_PER_INPUT_BYTE: usize = ${graph.rom.limits.opcostPerInputByte};\n` +
    `pub const V17_MAX_SCRIPT_BYTES: usize = ${graph.rom.limits.scriptBytes};\n` +
    `pub const V17_MAX_FUNCTION_IDENTIFIER_BYTES: usize = ${graph.rom.limits.functionIdentifierBytes};\n` +
    `pub const V17_CONSENSUS_TX_BYTES: usize = ${graph.rom.limits.consensusTransactionBytes};\n` +
    `pub const V17_FRI_FOLD_LOGS: &[u8] = &[${graph.foundation.friFoldLogs.join(", ")}];\n\n` +
    `pub const V17_FRI_FOLD_CHALLENGE_COUNTS: &[u8] = &[${graph.foundation.friFoldChallengeCounts.join(", ")}];\n\n` +
    `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n` +
    `pub struct RoundGrinding {\n` +
    `    pub id: &'static str,\n` +
    `    pub bits: u8,\n` +
    `}\n\n` +
    `pub const V17_ROUND_GRINDING: &[RoundGrinding] = &[\n${roundRows}\n];\n\n` +
    `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n` +
    `pub struct MerkleCommitment {\n` +
    `    pub id: &'static str,\n` +
    `    pub label: &'static str,\n` +
    `    pub log_rows: u8,\n` +
    `    pub row_bytes: usize,\n` +
    `    pub leaf_shards: u8,\n` +
    `    pub quartet_first: bool,\n` +
    `    pub verifier_cuts: &'static [u8],\n` +
    `}\n\n` +
    `pub const V17_MERKLE_COMMITMENTS: &[MerkleCommitment] = &[\n${merkleRows}\n];\n\n` +
    `#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n` +
    `pub struct ProofFrame {\n` +
    `    pub id: &'static str,\n` +
    `    pub offset_bytes: usize,\n` +
    `    pub item_bytes: usize,\n` +
    `    pub item_count: usize,\n` +
    `}\n\n` +
    `${frameConstants}\n\n` +
    `pub const V17_PROOF_FRAMES: &[ProofFrame] = &[\n${frameRows}\n];\n`;
}

function roleSemanticObject(
  kind: string,
  properties: Readonly<Record<string, unknown>> = {},
  required: readonly string[] = [],
): unknown {
  return {
    type: "object",
    additionalProperties: false,
    required: ["kind", ...required],
    properties: { kind: { const: kind }, ...properties },
  };
}

function roleSemanticSchema(): unknown {
  const index = { type: "integer", minimum: 0 };
  const matrix = { enum: V17_MATRIX_NAMES };
  return {
    oneOf: [
      roleSemanticObject("settlement"),
      roleSemanticObject("ood-air"),
      roleSemanticObject("batch-link-query", { query: index }, ["query"]),
      roleSemanticObject("public-boundary-inverses"),
      roleSemanticObject("proof-header"),
      roleSemanticObject("edge-append"),
      roleSemanticObject("sparse-nullifier", {
        root: { enum: ["absence", "used"] }, segment: { enum: [0, 1] },
      }, ["root", "segment"]),
      roleSemanticObject("public-boundary-sum"),
      roleSemanticObject("transcript", {
        part: { enum: V17_TRANSCRIPT_ROLE_PARTS },
      }, ["part"]),
      roleSemanticObject("query-schedule"),
      roleSemanticObject("opening-current"),
      roleSemanticObject("opening-global", {
        stage: { enum: ["current", "previous", "shape"] },
      }, ["stage"]),
      roleSemanticObject("opening-fri", {
        layer: index, stage: { const: "current" }, mappingShard: { enum: [0, 1] },
      }, ["layer", "stage", "mappingShard"]),
      roleSemanticObject("opening-fri", {
        layer: index, stage: { const: "shape" },
      }, ["layer", "stage"]),
      roleSemanticObject("fri-fold-query", { query: index }, ["query"]),
      roleSemanticObject("matrix-merkle-leaf", {
        matrix, shard: index, shards: { enum: [1, 2] },
      }, ["matrix", "shard", "shards"]),
      roleSemanticObject("matrix-merkle-parent", {
        matrix, stage: index,
      }, ["matrix", "stage"]),
      roleSemanticObject("fri-merkle-leaf", {
        layer: index, shard: index, shards: { enum: [1, 2] },
      }, ["layer", "shard", "shards"]),
      roleSemanticObject("fri-merkle-parent", {
        layer: index, stage: index,
      }, ["layer", "stage"]),
    ],
  };
}

export function buildV17VerifierPlanSchema(
  graph: V17ConstructionGraph = V17_CONSTRUCTION_GRAPH,
): unknown {
  return {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "ShieldKit/V17VerifierPlan/v1",
    type: "object",
    additionalProperties: false,
    required: ["schema", "protocolIdHex", "roleFamilies", "roles", "allocation", "rom"],
    properties: {
      schema: { const: "ShieldKit/V17VerifierPlan/v1" },
      protocolIdHex: { type: "string", pattern: "^[0-9a-f]{64}$" },
      roleFamilies: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["id", "kind", "semanticInstances", "ordinalSource", "proofCarrier",
            "defineBodyIdentity", "profiles", "description"],
          properties: {
            id: { type: "string", minLength: 1 },
            kind: { enum: V17_ROLE_KINDS },
            semanticInstances: {
              type: "array", minItems: 1, items: roleSemanticSchema(),
            },
            ordinalSource: { enum: ["singleton", "input-index", "generated-static"] },
            proofCarrier: { type: "boolean" },
            defineBodyIdentity: {
              enum: ["construction-independent", "construction-bound"],
            },
            profiles: { const: [0, 1, 2] },
            description: { type: "string", minLength: 1 },
          },
        },
      },
      roles: {
        type: "array",
        minItems: 1,
        items: {
          type: "object",
          additionalProperties: false,
          required: ["logicalInputIndex", "id", "familyId", "kind", "ordinal", "ordinalSource",
            "proofCarrier", "defineBodyIdentity", "profiles", "obligations", "semantic"],
          properties: {
            logicalInputIndex: { type: "integer", minimum: 0 },
            id: { type: "string", minLength: 1 },
            familyId: { type: "string", minLength: 1 },
            kind: { type: "string", minLength: 1 },
            semantic: roleSemanticSchema(),
            ordinal: { type: "integer", minimum: 0 },
            ordinalSource: { enum: ["singleton", "input-index", "generated-static"] },
            proofCarrier: { type: "boolean" },
            defineBodyIdentity: {
              enum: ["construction-independent", "construction-bound"],
            },
            profiles: { const: [0, 1, 2] },
            obligations: { type: "array", items: { type: "string", pattern: "^C(?:[1-9]|[12][0-9]|3[0-3])$" } },
          },
        },
      },
      allocation: {
        type: "object",
        additionalProperties: false,
        required: ["status", "strategy", "densityCredit", "baseEndpoint", "closure",
          "closureGenesis", "closureJoin", "closureTerminal", "closureTrace",
          "elasticNormalization", "elasticScaleUnits", "minimumProofBytes",
          "maximumProofBytes", "minimumProofBytesPerRole", "capacityLimitBytes",
          "capacityDerivation", "slackDistribution", "metadataEncoding", "proofRoleCount",
          "assignments"],
        properties: {
          status: { enum: ["unmeasured", "measured"] },
          strategy: { const: "base-plus-elastic-prefix" },
          densityCredit: { const: "max-profile-residual-proof-bytes" },
          baseEndpoint: { const: "sum-max-profile-residual-proof-bytes" },
          closure: { const: "coordinatewise-monotone-profile-envelope" },
          closureGenesis: { const: "canonical-bootstrap-affine-allocation" },
          closureJoin: { const: "profile-opcost-max-required-max-capacity-min" },
          closureTerminal: { const: "explicit-no-change-replay" },
          closureTrace: { const: "domain-separated-sha256-chain" },
          elasticNormalization: { const: "cumulative-floor-prefix-union" },
          elasticScaleUnits: { const: V17_ELASTIC_PREFIX_SCALE },
          minimumProofBytes: {
            anyOf: [{ type: "null" }, { type: "integer", minimum: 1,
              maximum: V17_MAXIMUM_CANONICAL_PROOF_BYTES - 1 }],
          },
          maximumProofBytes: { const: V17_MAXIMUM_CANONICAL_PROOF_BYTES },
          minimumProofBytesPerRole: { const: 256 },
          capacityLimitBytes: { const: 10_000 },
          capacityDerivation: { const: "canonical-proof-push-plus-linked-redeem-push" },
          slackDistribution: { const: "capacity-proportional-hamilton-role-order" },
          metadataEncoding: { const: "base19-elastic12-disabled-sequence" },
          proofRoleCount: { type: "integer", minimum: 1 },
          assignments: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["roleId", "basePrefixStart", "basePrefixEnd",
                "elasticPrefixStart", "elasticPrefixEnd", "requiredProofBytes",
                "capacityProofBytes", "maximumOperationCost"],
              properties: {
                roleId: { type: "string", minLength: 1 },
                basePrefixStart: { type: "integer", minimum: 0,
                  maximum: V17_MAXIMUM_CANONICAL_PROOF_BYTES - 1 },
                basePrefixEnd: { type: "integer", minimum: 1,
                  maximum: V17_MAXIMUM_CANONICAL_PROOF_BYTES },
                elasticPrefixStart: { type: "integer", minimum: 0,
                  maximum: V17_ELASTIC_PREFIX_SCALE },
                elasticPrefixEnd: { type: "integer", minimum: 0,
                  maximum: V17_ELASTIC_PREFIX_SCALE },
                requiredProofBytes: { type: "integer", minimum: 1 },
                capacityProofBytes: { type: "integer", minimum: 1, maximum: 10_000 },
                maximumOperationCost: { type: "integer", minimum: 1 },
              },
            },
          },
        },
      },
      rom: {
        type: "object",
        additionalProperties: false,
        required: ["status", "pageFormat", "payloadFormat", "bodyAccess", "eligibility",
          "bankIdentity", "deduplication", "promotion", "qualificationMeasurement",
          "functionIdentifiers", "packing", "placement", "limits", "pages"],
        properties: {
          status: { enum: ["unmeasured", "measured"] },
          pageFormat: { const: "p2sh32-authenticated-function-page-v1" },
          payloadFormat: { const: "skr1-directory-and-exact-bodies-v1" },
          bodyAccess: { const: "sibling-input-bytecode-canonical-slice" },
          eligibility: { const: "construction-independent-op-define-bodies" },
          bankIdentity: {
            const: graph.rom.bankIdentity,
          },
          deduplication: { const: "exact-byte-equality" },
          promotion: { const: "strict-positive-saving-in-every-profile" },
          qualificationMeasurement: { const: "post-link-all-profile-independent-bchn" },
          functionIdentifiers: {
            const: "minimal-positive-unsigned-be-earliest-static-occurrence-anchor",
          },
          packing: { const: "minimum-pages-then-semantic-anchor" },
          placement: { const: "after-proof-workers" },
          limits: {
            const: {
              scriptBytes: 10_000,
              elementBytes: 10_000,
              stackItems: 1_000,
              controlDepth: 100,
              functionIdentifierBytes: 7,
              opcostPerInputByte: 800,
              consensusTransactionBytes: 1_000_000,
            },
          },
          pages: {
            type: "array",
            items: {
              type: "object",
              additionalProperties: false,
              required: ["index", "inputIndex", "outputIndex", "sha256Hex", "bytes", "functionIds"],
              properties: {
                index: { type: "integer", minimum: 0 },
                inputIndex: { type: "integer", minimum: 0 },
                outputIndex: { type: "integer", minimum: 0 },
                sha256Hex: { type: "string", pattern: "^[0-9a-f]{64}$" },
                bytes: { type: "integer", minimum: 1, maximum: 10_000 },
                functionIds: {
                  type: "array",
                  uniqueItems: true,
                  items: {
                    type: "string",
                    pattern: "^(?:0[1-9a-f]|[1-9a-f][0-9a-f])(?:[0-9a-f]{2}){0,6}$",
                  },
                },
              },
            },
          },
        },
      },
    },
  };
}

/**
 * Compile the emitted Draft 2020-12 schema and validate the emitted plan.
 * This is a schema-conformance gate, not a substitute for graph validation.
 */
export function assertV17VerifierPlanConformsToSchema(args: {
  readonly plan: unknown;
  readonly schema: unknown;
}): void {
  const ajv = new Ajv2020({ allErrors: true, strict: true });
  const validate = ajv.compile(args.schema as object);
  if (!validate(args.plan)) {
    throw new Error(`v17 verifier plan schema: ${ajv.errorsText(validate.errors, {
      separator: "; ",
    })}`);
  }
  const pages = (args.plan as {
    readonly rom: {
      readonly pages: readonly { readonly index: number; readonly functionIds: readonly string[] }[];
    };
  }).rom.pages;
  const seenFunctionIds = new Set<string>();
  for (const page of pages) {
    let previous: string | undefined;
    for (const functionId of page.functionIds) {
      if (seenFunctionIds.has(functionId)) {
        throw new Error(`v17 verifier plan duplicate ROM function id ${functionId}`);
      }
      if (previous !== undefined) {
        const order = previous.length - functionId.length ||
          (previous < functionId ? -1 : previous > functionId ? 1 : 0);
        if (order >= 0) {
          throw new Error(`v17 verifier plan noncanonical ROM function id order at page ${page.index}`);
        }
      }
      seenFunctionIds.add(functionId);
      previous = functionId;
    }
  }
}

/** Fail closed before generation or qualification if graph-derived artifacts disagree. */
export function assertV17VerifierPlanSchemaConsistency(
  graph: V17ConstructionGraph = V17_CONSTRUCTION_GRAPH,
): void {
  assertV17VerifierPlanConformsToSchema({
    plan: buildV17VerifierPlan(graph),
    schema: buildV17VerifierPlanSchema(graph),
  });
}

/** Pure generation: callers choose whether to check or write these bytes. */
export function generateV17ConstructionArtifacts(
  graph: V17ConstructionGraph = V17_CONSTRUCTION_GRAPH,
): V17GeneratedArtifacts {
  validateV17ConstructionGraph(graph);
  const protocolIdHex = v17ProtocolIdHex(graph);
  const plan = buildV17VerifierPlan(graph);
  const planSchema = buildV17VerifierPlanSchema(graph);
  assertV17VerifierPlanConformsToSchema({ plan, schema: planSchema });
  const qualification = createPendingV17Qualification(protocolIdHex);
  return {
    "src/construction/generated/v17-layout.ts": typescriptLayout(graph, protocolIdHex),
    "src/construction/generated/v17-layout.rs": rustLayout(graph, protocolIdHex),
    "src/construction/generated/v17-verifier-plan.json": prettyCanonicalJson(plan),
    "src/construction/generated/v17-verifier-plan.schema.json": prettyCanonicalJson(planSchema),
    "src/construction/generated/v17-qualification.json": prettyCanonicalJson(qualification),
  };
}
